//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourGuideApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TourGuideApp.Resources.Languages.AppLang", typeof(AppLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả trải nghiệm.
        /// </summary>
        public static string AddPoiDesc {
            get {
                return ResourceManager.GetString("AddPoiDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi này có gì thú vị....
        /// </summary>
        public static string AddPoiDescPlaceholder {
            get {
                return ResourceManager.GetString("AddPoiDescPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📍 Lấy tọa độ hiện tại của bạn.
        /// </summary>
        public static string AddPoiGetLocation {
            get {
                return ResourceManager.GetString("AddPoiGetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấn để chụp hoặc chọn ảnh.
        /// </summary>
        public static string AddPoiImagePrompt {
            get {
                return ResourceManager.GetString("AddPoiImagePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vĩ độ (Lat).
        /// </summary>
        public static string AddPoiLat {
            get {
                return ResourceManager.GetString("AddPoiLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinh độ (Lng).
        /// </summary>
        public static string AddPoiLng {
            get {
                return ResourceManager.GetString("AddPoiLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên địa điểm.
        /// </summary>
        public static string AddPoiName {
            get {
                return ResourceManager.GetString("AddPoiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ví dụ: Chợ Bến Thành.
        /// </summary>
        public static string AddPoiNamePlaceholder {
            get {
                return ResourceManager.GetString("AddPoiNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bán kính hoạt động (m) - Mặc định.
        /// </summary>
        public static string AddPoiRadius {
            get {
                return ResourceManager.GetString("AddPoiRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi Yêu Cầu Chờ Duyệt.
        /// </summary>
        public static string AddPoiSubmit {
            get {
                return ResourceManager.GetString("AddPoiSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chia sẻ khám phá của bạn.
        /// </summary>
        public static string AddPoiTitle {
            get {
                return ResourceManager.GetString("AddPoiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ đường.
        /// </summary>
        public static string BtnDirections {
            get {
                return ResourceManager.GetString("BtnDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn một tour để bắt đầu khám phá.
        /// </summary>
        public static string ChooseTourSubtitle {
            get {
                return ResourceManager.GetString("ChooseTourSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📍 Lấy lại tọa độ GPS (nếu cần).
        /// </summary>
        public static string EditPoiGetLocation {
            get {
                return ResourceManager.GetString("EditPoiGetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấn để đổi ảnh khác (tùy chọn).
        /// </summary>
        public static string EditPoiImagePrompt {
            get {
                return ResourceManager.GetString("EditPoiImagePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu Và Chờ Duyệt Lại.
        /// </summary>
        public static string EditPoiSubmit {
            get {
                return ResourceManager.GetString("EditPoiSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin địa điểm.
        /// </summary>
        public static string EditPoiTitle {
            get {
                return ResourceManager.GetString("EditPoiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sài Gòn trong tầm tay.
        /// </summary>
        public static string ExploreSubtitle {
            get {
                return ResourceManager.GetString("ExploreSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá.
        /// </summary>
        public static string ExploreTitle {
            get {
                return ResourceManager.GetString("ExploreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa lưu địa điểm nào cả!.
        /// </summary>
        public static string FavEmpty {
            get {
                return ResourceManager.GetString("FavEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy dạo quanh bản đồ và thả tim nhé!.
        /// </summary>
        public static string FavEmptySub {
            get {
                return ResourceManager.GetString("FavEmptySub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đăng nhập để lưu trữ và xem lại những địa điểm bạn yêu thích nhé!.
        /// </summary>
        public static string FavGuestSubtitle {
            get {
                return ResourceManager.GetString("FavGuestSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔒 Dành riêng cho Thành viên.
        /// </summary>
        public static string FavGuestTitle {
            get {
                return ResourceManager.GetString("FavGuestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Nhập / Đăng Ký Ngay.
        /// </summary>
        public static string FavLoginButton {
            get {
                return ResourceManager.GetString("FavLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Những địa điểm bạn đã lưu lại.
        /// </summary>
        public static string FavSubtitle {
            get {
                return ResourceManager.GetString("FavSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Góc Yêu Thích ❤️.
        /// </summary>
        public static string FavTitle {
            get {
                return ResourceManager.GetString("FavTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lộ trình nổi bật.
        /// </summary>
        public static string FeaturedTours {
            get {
                return ResourceManager.GetString("FeaturedTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá tự do.
        /// </summary>
        public static string FreeExploration {
            get {
                return ResourceManager.GetString("FreeExploration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎧 Nghe Audio.
        /// </summary>
        public static string ListenAudio {
            get {
                return ResourceManager.GetString("ListenAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám Phá Ngay (Ẩn Danh).
        /// </summary>
        public static string LoginAnonymous {
            get {
                return ResourceManager.GetString("LoginAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Nhập.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có tài khoản?.
        /// </summary>
        public static string LoginNoAccount {
            get {
                return ResourceManager.GetString("LoginNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOẶC.
        /// </summary>
        public static string LoginOr {
            get {
                return ResourceManager.GetString("LoginOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký ngay.
        /// </summary>
        public static string LoginRegisterNow {
            get {
                return ResourceManager.GetString("LoginRegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá thế giới theo cách của bạn.
        /// </summary>
        public static string LoginSubtitle {
            get {
                return ResourceManager.GetString("LoginSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string LoginUsername {
            get {
                return ResourceManager.GetString("LoginUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tính....
        /// </summary>
        public static string MainCalculating {
            get {
                return ResourceManager.GetString("MainCalculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các điểm trong khu vực.
        /// </summary>
        public static string MainSubtitle {
            get {
                return ResourceManager.GetString("MainSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm Thuyết Minh.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📍 Chỉ đường ngoài.
        /// </summary>
        public static string MapsExternal {
            get {
                return ResourceManager.GetString("MapsExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗺️ Dẫn đường lộ trình này.
        /// </summary>
        public static string MapsThisRoute {
            get {
                return ResourceManager.GetString("MapsThisRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ.
        /// </summary>
        public static string MapTabTitle {
            get {
                return ResourceManager.GetString("MapTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TẢI XUỐNG NGAY.
        /// </summary>
        public static string OfflineBtnDownload {
            get {
                return ResourceManager.GetString("OfflineBtnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP. Hồ Chí Minh.
        /// </summary>
        public static string OfflineCity {
            get {
                return ResourceManager.GetString("OfflineCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải dữ liệu để sử dụng bản đồ và nghe thuyết minh không cần mạng Internet..
        /// </summary>
        public static string OfflineDesc {
            get {
                return ResourceManager.GetString("OfflineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dung lượng dự kiến: ~50MB.
        /// </summary>
        public static string OfflineSize {
            get {
                return ResourceManager.GetString("OfflineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa tải.
        /// </summary>
        public static string OfflineStatusPending {
            get {
                return ResourceManager.GetString("OfflineStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản Đồ Ngoại Tuyến.
        /// </summary>
        public static string OfflineTitle {
            get {
                return ResourceManager.GetString("OfflineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Chưa cấp quyền Camera.
        /// </summary>
        public static string QrCameraDenied {
            get {
                return ResourceManager.GetString("QrCameraDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sếp phải cho phép dùng Camera thì mới quét mã QR được nhé!.
        /// </summary>
        public static string QrCameraErrorDesc {
            get {
                return ResourceManager.GetString("QrCameraErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi Camera.
        /// </summary>
        public static string QrCameraErrorTitle {
            get {
                return ResourceManager.GetString("QrCameraErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã QR này không khớp với địa điểm nào. Hãy thử đồng bộ lại dữ liệu..
        /// </summary>
        public static string QrNotFoundDesc {
            get {
                return ResourceManager.GetString("QrNotFoundDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy.
        /// </summary>
        public static string QrNotFoundTitle {
            get {
                return ResourceManager.GetString("QrNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đưa mã QR vào khung.
        /// </summary>
        public static string QRSubtitle {
            get {
                return ResourceManager.GetString("QRSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quét mã QR.
        /// </summary>
        public static string QRTitle {
            get {
                return ResourceManager.GetString("QRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ đọc:.
        /// </summary>
        public static string ReadLanguage {
            get {
                return ResourceManager.GetString("ReadLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại Đăng nhập.
        /// </summary>
        public static string RegisterBackToLogin {
            get {
                return ResourceManager.GetString("RegisterBackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Ký Mới.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu.
        /// </summary>
        public static string RegisterConfirmPassword {
            get {
                return ResourceManager.GetString("RegisterConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham gia cộng đồng khám phá.
        /// </summary>
        public static string RegisterSubtitle {
            get {
                return ResourceManager.GetString("RegisterSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Tài Khoản.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💔 Bỏ yêu thích.
        /// </summary>
        public static string RemoveFav {
            get {
                return ResourceManager.GetString("RemoveFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LỘ TRÌNH CHI TIẾT.
        /// </summary>
        public static string RouteDetails {
            get {
                return ResourceManager.GetString("RouteDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm địa điểm....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ngôn ngữ.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin ứng dụng.
        /// </summary>
        public static string SetAppInfo {
            get {
                return ResourceManager.GetString("SetAppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự động phát thuyết minh.
        /// </summary>
        public static string SetAutoAudio {
            get {
                return ResourceManager.GetString("SetAutoAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string SetLanguage {
            get {
                return ResourceManager.GetString("SetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngoại tuyến.
        /// </summary>
        public static string SetOffline {
            get {
                return ResourceManager.GetString("SetOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Thêm mới.
        /// </summary>
        public static string SettingsAddNew {
            get {
                return ResourceManager.GetString("SettingsAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập / Đăng ký.
        /// </summary>
        public static string SettingsAuthLogin {
            get {
                return ResourceManager.GetString("SettingsAuthLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất tài khoản.
        /// </summary>
        public static string SettingsAuthLogout {
            get {
                return ResourceManager.GetString("SettingsAuthLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📭 Bạn chưa đóng góp địa điểm nào..
        /// </summary>
        public static string SettingsEmptyPoi {
            get {
                return ResourceManager.GetString("SettingsEmptyPoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập để chia sẻ những địa điểm thú vị của riêng bạn lên bản đồ nhé!.
        /// </summary>
        public static string SettingsGuestSubtitle {
            get {
                return ResourceManager.GetString("SettingsGuestSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Góc đóng góp.
        /// </summary>
        public static string SettingsGuestTitle {
            get {
                return ResourceManager.GetString("SettingsGuestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào,.
        /// </summary>
        public static string SettingsHello {
            get {
                return ResourceManager.GetString("SettingsHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa điểm của tôi.
        /// </summary>
        public static string SettingsMyPois {
            get {
                return ResourceManager.GetString("SettingsMyPois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        public static string SetTitle {
            get {
                return ResourceManager.GetString("SetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên bản 1.0.
        /// </summary>
        public static string SetVersion {
            get {
                return ResourceManager.GetString("SetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛑 Dừng thuyết minh.
        /// </summary>
        public static string StopAudio {
            get {
                return ResourceManager.GetString("StopAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu thích.
        /// </summary>
        public static string TabFavorite {
            get {
                return ResourceManager.GetString("TabFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ.
        /// </summary>
        public static string TabMap {
            get {
                return ResourceManager.GetString("TabMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm.
        /// </summary>
        public static string TabPlaces {
            get {
                return ResourceManager.GetString("TabPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR.
        /// </summary>
        public static string TabQR {
            get {
                return ResourceManager.GetString("TabQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        public static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗺️ Xem trên Bản đồ App.
        /// </summary>
        public static string ViewOnAppMap {
            get {
                return ResourceManager.GetString("ViewOnAppMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào mừng bạn đến với lộ trình {0}. Thời gian dự kiến là {1}..
        /// </summary>
        public static string WelcomeTourAudio {
            get {
                return ResourceManager.GetString("WelcomeTourAudio", resourceCulture);
            }
        }
    }
}
