//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourGuideApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TourGuideApp.Resources.Languages.AppLang", typeof(AppLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ đường.
        /// </summary>
        public static string BtnDirections {
            get {
                return ResourceManager.GetString("BtnDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn một tour để bắt đầu khám phá.
        /// </summary>
        public static string ChooseTourSubtitle {
            get {
                return ResourceManager.GetString("ChooseTourSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sài Gòn trong tầm tay.
        /// </summary>
        public static string ExploreSubtitle {
            get {
                return ResourceManager.GetString("ExploreSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá.
        /// </summary>
        public static string ExploreTitle {
            get {
                return ResourceManager.GetString("ExploreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa lưu địa điểm nào cả!.
        /// </summary>
        public static string FavEmpty {
            get {
                return ResourceManager.GetString("FavEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy dạo quanh bản đồ và thả tim nhé!.
        /// </summary>
        public static string FavEmptySub {
            get {
                return ResourceManager.GetString("FavEmptySub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Những địa điểm bạn đã lưu lại.
        /// </summary>
        public static string FavSubtitle {
            get {
                return ResourceManager.GetString("FavSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Góc Yêu Thích ❤️.
        /// </summary>
        public static string FavTitle {
            get {
                return ResourceManager.GetString("FavTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lộ trình nổi bật.
        /// </summary>
        public static string FeaturedTours {
            get {
                return ResourceManager.GetString("FeaturedTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá tự do.
        /// </summary>
        public static string FreeExploration {
            get {
                return ResourceManager.GetString("FreeExploration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎧 Nghe Audio.
        /// </summary>
        public static string ListenAudio {
            get {
                return ResourceManager.GetString("ListenAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tính....
        /// </summary>
        public static string MainCalculating {
            get {
                return ResourceManager.GetString("MainCalculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các điểm trong khu vực.
        /// </summary>
        public static string MainSubtitle {
            get {
                return ResourceManager.GetString("MainSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm Thuyết Minh.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📍 Chỉ đường ngoài.
        /// </summary>
        public static string MapsExternal {
            get {
                return ResourceManager.GetString("MapsExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗺️ Dẫn đường lộ trình này.
        /// </summary>
        public static string MapsThisRoute {
            get {
                return ResourceManager.GetString("MapsThisRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ.
        /// </summary>
        public static string MapTabTitle {
            get {
                return ResourceManager.GetString("MapTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TẢI XUỐNG NGAY.
        /// </summary>
        public static string OfflineBtnDownload {
            get {
                return ResourceManager.GetString("OfflineBtnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP. Hồ Chí Minh.
        /// </summary>
        public static string OfflineCity {
            get {
                return ResourceManager.GetString("OfflineCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải dữ liệu để sử dụng bản đồ và nghe thuyết minh không cần mạng Internet..
        /// </summary>
        public static string OfflineDesc {
            get {
                return ResourceManager.GetString("OfflineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dung lượng dự kiến: ~50MB.
        /// </summary>
        public static string OfflineSize {
            get {
                return ResourceManager.GetString("OfflineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa tải.
        /// </summary>
        public static string OfflineStatusPending {
            get {
                return ResourceManager.GetString("OfflineStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản Đồ Ngoại Tuyến.
        /// </summary>
        public static string OfflineTitle {
            get {
                return ResourceManager.GetString("OfflineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đưa mã QR vào khung.
        /// </summary>
        public static string QRSubtitle {
            get {
                return ResourceManager.GetString("QRSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quét mã QR.
        /// </summary>
        public static string QRTitle {
            get {
                return ResourceManager.GetString("QRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ đọc:.
        /// </summary>
        public static string ReadLanguage {
            get {
                return ResourceManager.GetString("ReadLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💔 Bỏ yêu thích.
        /// </summary>
        public static string RemoveFav {
            get {
                return ResourceManager.GetString("RemoveFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LỘ TRÌNH CHI TIẾT.
        /// </summary>
        public static string RouteDetails {
            get {
                return ResourceManager.GetString("RouteDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm địa điểm....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ngôn ngữ.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin ứng dụng.
        /// </summary>
        public static string SetAppInfo {
            get {
                return ResourceManager.GetString("SetAppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự động phát thuyết minh.
        /// </summary>
        public static string SetAutoAudio {
            get {
                return ResourceManager.GetString("SetAutoAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string SetLanguage {
            get {
                return ResourceManager.GetString("SetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngoại tuyến.
        /// </summary>
        public static string SetOffline {
            get {
                return ResourceManager.GetString("SetOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        public static string SetTitle {
            get {
                return ResourceManager.GetString("SetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên bản 1.0.
        /// </summary>
        public static string SetVersion {
            get {
                return ResourceManager.GetString("SetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛑 Dừng thuyết minh.
        /// </summary>
        public static string StopAudio {
            get {
                return ResourceManager.GetString("StopAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu thích.
        /// </summary>
        public static string TabFavorite {
            get {
                return ResourceManager.GetString("TabFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ.
        /// </summary>
        public static string TabMap {
            get {
                return ResourceManager.GetString("TabMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm.
        /// </summary>
        public static string TabPlaces {
            get {
                return ResourceManager.GetString("TabPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR.
        /// </summary>
        public static string TabQR {
            get {
                return ResourceManager.GetString("TabQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        public static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗺️ Xem trên Bản đồ App.
        /// </summary>
        public static string ViewOnAppMap {
            get {
                return ResourceManager.GetString("ViewOnAppMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào mừng bạn đến với lộ trình {0}. Thời gian dự kiến là {1}..
        /// </summary>
        public static string WelcomeTourAudio {
            get {
                return ResourceManager.GetString("WelcomeTourAudio", resourceCulture);
            }
        }
    }
}
