// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourGuideAdmin.Models;

#nullable disable

namespace TourGuideAdmin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402154146_AddTourTable")]
    partial class AddTourTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("TourGuideAdmin.Models.POI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description_EN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description_JA")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description_KO")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description_VI")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description_ZH")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPlayedTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name_EN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name_JA")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name_KO")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name_VI")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name_ZH")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TourId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TriggerRadius")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("POIs");
                });

            modelBuilder.Entity("TourGuideAdmin.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description_EN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description_JA")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description_KO")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description_VI")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description_ZH")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name_EN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name_JA")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name_KO")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name_VI")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name_ZH")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
